language: node_js
node_js:
- node
- '6'
- '5.12'
env:
  global:
  - secure: ys8pLVygLoxOhTBfZvo32HTIeoWz50SHD0fkrYUhxVZkZbjMrw43LGIDtJ6zIbBS3m3j6vEKE33fVWxyCf/lHHAxKrm0y2wnBfF2KkInDhP/IgozSu4Bkto1dZOGD7lWiPJIa1cAtdN1z2jHFOnNK9WYCt8shX1k8R4SBiyeAMRBMwhI+j4w8OGgKs+E5ucF+zq3sQy5Qp4n0Z6eiHqVnp6iOWCPh7Dj5vRQ331xG5wNfXpggpUoH1fGIkOG5qbVPjl0/Q/zlA3xZycWHijWccPs/JjL7mPTn9ZN4vhFYdM9VPL96VIJ4rI6wirc1vzZVnpmju5lFHJ0fnUij9YYCWInBdN3/+mEdIcedCAENvymUyhACxZo3okbCMpOLMpNhGgstDgHD0TX3iTcEZ1pKYMUHYVcOVy2Hf/w2Z7B3PiudbDcg38Fmls0lFgYVq88XMcowZGAjATJNDwQuVM9NjWT8ghhhlS0UtG+b234zsDwjsPyhz0aEuJgiVW4NGNJHopd+wI3N7H0pwFZ8ELExPmrUepCFaDskPNeQAcc0wqM3nWkCsaYoEbt09njsqzdWnCwO8rSfZUA9oUzlJPUEqxu7cqlpt9ObpNV0jZSnSLaIDztnObvGkJtULaTfz6uoBB/cLb6hpvQRR/b1r7ShCM6FA3ZHB3lNskXz0SWmqo=
  - secure: eCq39zYU7zJj2jfxKJamnU4lofoC9AMXSCNHdotAQPl0SBu+HN9CXmOn5YHmeIC6MQlkI1SMfWsw/VpqFpTaRsQu0SylB9XpOtK8pdp5Y0EOxhOGn5J8TXX1vR0vgBXo05xHQ2/UG5OJ3cZ808rknL/uUzAL/8jLQ1tRRv3UdXXuLzZOLSwrY0YYf0u0QEkq5CO/1Yt4gd1UvbskjOlPQonjBJHaXER4PRhQRwUsaVXsYV0jNF77OWEq5RoZVsu948dYEqMvnvUVVg05FIE9Q4JNziHrTD6qp5GB8O8M8by/MzE+Mu/inkYWBo/lKkz7EFNiScoOSv/06vwIMV6srn/VjrmaYm2r5zXEU6o7IuypTr8bjOBHX148I4AtfjC8GaX1StnCru6AGF/hd2Sv40PJwhaygMdHZ7QUyMHLg8TxxQ/7yyxacHG83KWmasuxcgxu6nVmQ7mzNXLb96rONxsZ3PJGdPDZQ3W9mhhO6KrykRyU+Xa/2LiW1/WzqSFwiWgVuXlhD2dVFqgtJ2aqnNhVKAZ151oG/4ybDR5VRQwW6hua3s9wRbb9d/Bx/P4nTE298IH1U9Z1PDwdmFuNPcWSBf+JbGa1DaCOlNaOqPr8DyM43wH5jhMjUtVyKKo4X63Agfg+eDSA2ywDHwTLC5kh05mbjab31YzJmW2qI/E=
before_install:
  - echo $JWT_SECRET
sudo: required
services:
  - docker

